### ISSUE TITLE
Error start container.

### ISSUE THREAD

**Issue by TalismanFR** [r-erema/docker#1]
Hello!

The container at start show an error.
/usr/local/bin/docker-php-entrypoint: exec: line 9: php-fpm: not found.

**Comment by TalismanFR** [comment]
In php-fpm Dockerfile need change  `FROM php:7.4-rc-cli-alpine` to `FROM php:7.4-rc-fpm-alpine`

**Comment by r-erema** [comment]
Thanks! Fixed

**Comment by TalismanFR** [comment]
Cool!
